# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", path: "pg_config.sh"
  # config.vm.box = "hashicorp/precise32"
  config.vm.box = "ubuntu/trusty32"
  config.vm.network "private_network", ip: "192.168.50.4",
    auto_config: false
  # config.vm.network "private_network", ip: "10.3.3.4"
  # config.vm.network "private_network", ip: "192.168.3."
  # config.vm.network "forwarded_port", guest: 5432, host: 15432
  # config.vm.network "forwarded_port", guest: 5000, host: 5000
end
